repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run ruff check --fix
        language: system
        types_or: [python, pyi]
      - id: black
        name: black
        entry: uv run black
        language: system
        types_or: [python, pyi]
