from typing import Literal

from literals import NotificationKind, Provider
from notification_providers import get_notification_provider


async def send_notification(
    kind: NotificationKind,
    provider: Provider,
    title: str,
    summary: str,
    channels: list[str],
    details: dict[str, object] | None = None,
    risk_level: Literal["low", "medium", "high"] = "low",
    dry_run: bool = True,
) -> dict:
    """
    Send an AI-generated developer notification to a configured chat provider.

    kind: Notification type.
    provider: Messaging provider to use.
    title: Short notification title.
    summary: Human-readable summary generated by Codex.
    channels: Allowed internal chat channels for the selected provider.
    details: Optional structured notification-specific data.
    risk_level: low, medium, or high.
    dry_run: If true, only preview the payload without sending.
    """

    try:
        notification_provider = get_notification_provider(provider=provider)
    except ValueError as error:
        return {
            "ok": False,
            "error": str(error),
        }

    allowed_channels = notification_provider.allowed_channels
    invalid_channels = sorted(set(channels) - allowed_channels)
    if invalid_channels:
        return {
            "ok": False,
            "error": f"These {provider} channels are not allowed: {invalid_channels}",
            "allowed_channels": sorted(allowed_channels),
        }

    payload = {
        "kind": kind,
        "provider": provider,
        "title": title,
        "summary": summary,
        "channels": channels,
        "details": details or {},
        "risk_level": risk_level,
    }

    if dry_run:
        return {
            "ok": True,
            "dry_run": True,
            "payload": payload,
        }

    try:
        result = await notification_provider.send(payload)
    except ValueError as error:
        return {
            "ok": False,
            "error": str(error),
        }

    return {
        "ok": True,
        "dry_run": False,
        "result": result,
    }
